### ISSUE TITLE
queryMx ENODATA

### ISSUE THREAD

**Issue by ddtraceweb** [nmanousos/email-existence#41]
Hello,

i have this error, do you have an idea of problem ?

{ Error: queryMx ENODATA voila.fr

Thanks 👍

**Comment by knoxcard** [comment]
This is the problem...

DNS Record not found
https://mxtoolbox.com/SuperTool.aspx?action=mx%3avoila.fr&run=toolpage

**Comment by knoxcard** [comment]
Close ticket?
